import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:gstore/core/image/svg_intrinsic_size.dart';

void main() {
  group('parseSvgIntrinsicSize', () {
    test('<svg width="104" height="20"> → (104,20)', () {
      final bytes = utf8.encode(
        '<svg xmlns="http://www.w3.org/2000/svg" width="104" height="20">'
        '<rect width="104" height="20" fill="red"/></svg>',
      );
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 20);
    });

    test('width="104px" height="20px" → px 后缀剥离 → (104,20)', () {
      final bytes = utf8.encode('<svg width="104px" height="20px"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 20);
    });

    test('小数尺寸 → double 解析', () {
      final bytes = utf8.encode('<svg width="12.5" height="7.25"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 12.5);
      expect(size.height, 7.25);
    });

    test('仅 viewBox="0 0 104 20" → (104,20)', () {
      final bytes = utf8.encode('<svg viewBox="0 0 104 20"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 20);
    });

    test('width="50%" + viewBox → width 无效，viewBox 兜底', () {
      final bytes =
          utf8.encode('<svg width="50%" viewBox="0 0 104 20"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 20);
    });

    test('仅 width + viewBox → viewBox 宽高比补高', () {
      final bytes =
          utf8.encode('<svg width="104" viewBox="0 0 20 10"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 52); // 104 * 10/20
    });

    test('仅 height + viewBox → viewBox 宽高比补宽', () {
      final bytes =
          utf8.encode('<svg height="10" viewBox="0 0 20 10"></svg>');
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 20); // 10 * 20/10
      expect(size.height, 10);
    });

    test('width+viewBox 并存 → width/height 优先', () {
      final bytes = utf8.encode(
        '<svg width="104" height="20" viewBox="0 0 100 100"></svg>',
      );
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 104);
      expect(size.height, 20);
    });

    test('无任何尺寸属性 → null', () {
      final bytes = utf8.encode('<svg xmlns="http://www.w3.org/2000/svg"></svg>');
      expect(parseSvgIntrinsicSize(bytes), isNull);
    });

    test('width="50%" 无 viewBox → null', () {
      final bytes = utf8.encode('<svg width="50%"></svg>');
      expect(parseSvgIntrinsicSize(bytes), isNull);
    });

    test('width="auto" 非法 → null', () {
      final bytes = utf8.encode('<svg width="auto" height="20"></svg>');
      expect(parseSvgIntrinsicSize(bytes), isNull);
    });

    test('<?xml 声明前缀 + viewBox → (10,5)', () {
      final bytes = utf8.encode(
        '<?xml version="1.0"?>\n<svg viewBox="0 0 10 5"></svg>',
      );
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 10);
      expect(size.height, 5);
    });

    test('BOM + 注释前缀 → 正常解析', () {
      final bytes = Uint8List.fromList([
        0xEF, 0xBB, 0xBF, // UTF-8 BOM
        ...utf8.encode('<!-- generated by tool --><svg width="30" height="10"></svg>'),
      ]);
      final size = parseSvgIntrinsicSize(bytes);
      expect(size, isNotNull);
      expect(size!.width, 30);
      expect(size.height, 10);
    });

    test('非 SVG 文本 → null', () {
      final bytes = utf8.encode('<html><body>hello</body></html>');
      expect(parseSvgIntrinsicSize(bytes), isNull);
    });

    test('空 bytes → null', () {
      expect(parseSvgIntrinsicSize(Uint8List(0)), isNull);
    });
  });
}
