// This file is @generated by prost-build.
/// ============ 请求信封（类似 HTTP Request） ============
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnvelopeRequest {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    /// --- 路由头（代替 URL）---
    #[prost(string, tag = "2")]
    pub module: ::prost::alloc::string::String,
    /// 空 = 模块级静态调用
    #[prost(string, tag = "3")]
    pub instance: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method: ::prost::alloc::string::String,
    /// --- 元数据 ---
    #[prost(string, tag = "5")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub timestamp_ms: i64,
    #[prost(enumeration = "PayloadFormat", tag = "7")]
    pub payload_format: i32,
    #[prost(map = "string, string", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "10")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// ============ 响应信封（类似 HTTP Response） ============
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnvelopeResponse {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
    /// --- 状态（仿 HTTP 语义分层）---
    #[prost(enumeration = "StatusCode", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    /// --- 元数据 ---
    #[prost(int64, tag = "6")]
    pub timestamp_ms: i64,
    #[prost(int64, tag = "7")]
    pub duration_ms: i64,
    #[prost(map = "string, string", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "10")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// ============ 取消消息（主动中断长任务） ============
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvelopeCancel {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub module: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub instance: ::prost::alloc::string::String,
    /// 可为空 = 取消该实例所有 in-flight
    #[prost(string, tag = "5")]
    pub method: ::prost::alloc::string::String,
    #[prost(enumeration = "CancelReason", tag = "6")]
    pub reason: i32,
}
/// ============ payload 编码格式 ============
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PayloadFormat {
    /// 默认：域 schema 也是 proto
    PayloadProtobuf = 0,
    /// 调试/快速原型
    PayloadJson = 1,
    /// 纯字节透传（QR luma 帧直接裸传）
    PayloadRawBytes = 2,
}
impl PayloadFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PayloadProtobuf => "PAYLOAD_PROTOBUF",
            Self::PayloadJson => "PAYLOAD_JSON",
            Self::PayloadRawBytes => "PAYLOAD_RAW_BYTES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PAYLOAD_PROTOBUF" => Some(Self::PayloadProtobuf),
            "PAYLOAD_JSON" => Some(Self::PayloadJson),
            "PAYLOAD_RAW_BYTES" => Some(Self::PayloadRawBytes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CancelReason {
    CancelUser = 0,
    CancelTimeout = 1,
    CancelShutdown = 2,
}
impl CancelReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CancelUser => "CANCEL_USER",
            Self::CancelTimeout => "CANCEL_TIMEOUT",
            Self::CancelShutdown => "CANCEL_SHUTDOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CANCEL_USER" => Some(Self::CancelUser),
            "CANCEL_TIMEOUT" => Some(Self::CancelTimeout),
            "CANCEL_SHUTDOWN" => Some(Self::CancelShutdown),
            _ => None,
        }
    }
}
/// ============ 状态码规范 ============
/// 同 HTTP 逻辑：status 决定处理策略（重试/降级/提示/报 bug），
/// error_code 决定具体原因（日志与排障）。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StatusCode {
    /// 0 占位（proto3 开放枚举强制首值为 0；不用作业务状态）
    StatusUnknown = 0,
    /// 2xx 成功
    StatusOk = 200,
    StatusCreated = 201,
    /// 3xx 需要客户端配合（流程，非错误）
    StatusModuleNotLoaded = 301,
    StatusInstanceExpired = 302,
    /// 4xx 调用方错误
    StatusBadRequest = 400,
    StatusModuleNotFound = 404,
    StatusMethodNotFound = 405,
    StatusInstanceNotFound = 410,
    StatusInvalidArgument = 422,
    StatusVersionMismatch = 426,
    /// 499 主动取消（区别于 5xx 错误）
    StatusAborted = 499,
    /// 5xx 模块内部错误
    StatusInternalError = 500,
    StatusPanicCaught = 5001,
    StatusResourceExhausted = 507,
    StatusTimeout = 504,
}
impl StatusCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StatusUnknown => "STATUS_UNKNOWN",
            Self::StatusOk => "STATUS_OK",
            Self::StatusCreated => "STATUS_CREATED",
            Self::StatusModuleNotLoaded => "STATUS_MODULE_NOT_LOADED",
            Self::StatusInstanceExpired => "STATUS_INSTANCE_EXPIRED",
            Self::StatusBadRequest => "STATUS_BAD_REQUEST",
            Self::StatusModuleNotFound => "STATUS_MODULE_NOT_FOUND",
            Self::StatusMethodNotFound => "STATUS_METHOD_NOT_FOUND",
            Self::StatusInstanceNotFound => "STATUS_INSTANCE_NOT_FOUND",
            Self::StatusInvalidArgument => "STATUS_INVALID_ARGUMENT",
            Self::StatusVersionMismatch => "STATUS_VERSION_MISMATCH",
            Self::StatusAborted => "STATUS_ABORTED",
            Self::StatusInternalError => "STATUS_INTERNAL_ERROR",
            Self::StatusPanicCaught => "STATUS_PANIC_CAUGHT",
            Self::StatusResourceExhausted => "STATUS_RESOURCE_EXHAUSTED",
            Self::StatusTimeout => "STATUS_TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNKNOWN" => Some(Self::StatusUnknown),
            "STATUS_OK" => Some(Self::StatusOk),
            "STATUS_CREATED" => Some(Self::StatusCreated),
            "STATUS_MODULE_NOT_LOADED" => Some(Self::StatusModuleNotLoaded),
            "STATUS_INSTANCE_EXPIRED" => Some(Self::StatusInstanceExpired),
            "STATUS_BAD_REQUEST" => Some(Self::StatusBadRequest),
            "STATUS_MODULE_NOT_FOUND" => Some(Self::StatusModuleNotFound),
            "STATUS_METHOD_NOT_FOUND" => Some(Self::StatusMethodNotFound),
            "STATUS_INSTANCE_NOT_FOUND" => Some(Self::StatusInstanceNotFound),
            "STATUS_INVALID_ARGUMENT" => Some(Self::StatusInvalidArgument),
            "STATUS_VERSION_MISMATCH" => Some(Self::StatusVersionMismatch),
            "STATUS_ABORTED" => Some(Self::StatusAborted),
            "STATUS_INTERNAL_ERROR" => Some(Self::StatusInternalError),
            "STATUS_PANIC_CAUGHT" => Some(Self::StatusPanicCaught),
            "STATUS_RESOURCE_EXHAUSTED" => Some(Self::StatusResourceExhausted),
            "STATUS_TIMEOUT" => Some(Self::StatusTimeout),
            _ => None,
        }
    }
}
