// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// F-Droid 应用信息
class AppInfo {
  final String packageName;
  final String name;
  final String summary;
  final String icon;
  final String? license;
  final String? authorName;
  final String? sourceCode;
  final String? webSite;
  final List<String> categories;
  final PlatformInt64? added;
  final PlatformInt64? lastUpdated;

  /// 原始 metadata JSON 字符串
  final String? metadata;

  /// 原始 versions JSON 字符串
  final String? versions;

  const AppInfo({
    required this.packageName,
    required this.name,
    required this.summary,
    required this.icon,
    this.license,
    this.authorName,
    this.sourceCode,
    this.webSite,
    required this.categories,
    this.added,
    this.lastUpdated,
    this.metadata,
    this.versions,
  });

  @override
  int get hashCode =>
      packageName.hashCode ^
      name.hashCode ^
      summary.hashCode ^
      icon.hashCode ^
      license.hashCode ^
      authorName.hashCode ^
      sourceCode.hashCode ^
      webSite.hashCode ^
      categories.hashCode ^
      added.hashCode ^
      lastUpdated.hashCode ^
      metadata.hashCode ^
      versions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          packageName == other.packageName &&
          name == other.name &&
          summary == other.summary &&
          icon == other.icon &&
          license == other.license &&
          authorName == other.authorName &&
          sourceCode == other.sourceCode &&
          webSite == other.webSite &&
          categories == other.categories &&
          added == other.added &&
          lastUpdated == other.lastUpdated &&
          metadata == other.metadata &&
          versions == other.versions;
}

/// 下载结果
class DownloadResult {
  final int totalApps;
  final int downloadTimeMs;

  const DownloadResult({
    required this.totalApps,
    required this.downloadTimeMs,
  });

  @override
  int get hashCode => totalApps.hashCode ^ downloadTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadResult &&
          runtimeType == other.runtimeType &&
          totalApps == other.totalApps &&
          downloadTimeMs == other.downloadTimeMs;
}
