on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' ./pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch latest release from Suno2/Gstore-Repo
        id: fetch_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.repos.getLatestRelease({
              owner: 'sunO2',
              repo: 'GStore-Repositorys'
            });
            core.setOutput('release_tarball_url', response.data.tarball_url);

      - name: Download latest release tarball
        run: |
          wget -O Gstore-Repo.tar.gz ${{ steps.fetch_latest_release.outputs.release_tarball_url }}

      - name: Extract apps.db from tarball
        run: |
          mkdir -p Gstore-Repo
          tar -xzf Gstore-Repo.tar.gz -C Gstore-Repo --strip-components=1

      - name: Copy apps.db to assets/app/db/
        run: |
          cp Gstore-Repo/assets/app/db/apps.db assets/app/db/

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --no-shrink --target-platform android-arm,android-arm64,android-x64 --split-per-abi 
      - run: flutter build appbundle
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          body: 测试
          draft: false
          prerelease: false
      - name: Upload Release AAB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/zip
      - name: Upload Release APK32
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          asset_name: GStore-armeabi-v7a-release.apk
          asset_content_type: application/zip
      - name: Upload Release APK64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: GStore-arm64-v8a-release.apk 
          asset_content_type: application/zip
      - name: Upload Release x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-x86_64-release.apk
          asset_name: GStore-x86_64-release.apk
          asset_content_type: application/zip
